language: csharp
dist: trusty
sudo: false
dotnet: 2.1.301

matrix:
  fast_finish: true
  
  include:
    - os: linux
      mono: 5.8.0
    - os: linux
      mono: weekly
    - os: linux
      mono: latest
    - os: osx
      osx_image: xcode9.3
      mono: 5.4.1
    - os: osx
      osx_image: xcode9.3
      mono: 5.8.0
    - os: osx
      osx_image: xcode9.3
      mono: latest

  allow_failures:
    - mono: weekly
    - mono: latest

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_install:
  - dotnet tool install fake-cli -g

script:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1-api
  - fake build