language: csharp
dist: bionic
dotnet: 3.1.200

matrix:
  fast_finish: true
  
  include:
    - os: linux
      mono: 5.8.0
    - os: linux
      mono: 6.0.0
    - os: linux
      mono: latest
    - os: osx
      osx_image: xcode9.3
      mono: latest

  allow_failures:
    - mono: latest
    - mono: 5.8.0

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

script:
  - ./fake build
