---
language: fsharp

dist: trusty
sudo: required

os:
 - osx
 - linux

install:
 # See details at https://github.com/NuGet/Home/issues/2163
 # this may be required because of an underlying bug in mono. It may
 # also be induced by us because we have an extra nuget.config source.
 - ulimit -n 2048
 - rvm install 2.2.3
 - gem install bundler

script:
 - bundle
 - bundle exec rake

matrix:
  include:
    - dotnet: 1.0.4
      mono: none
    - mono: 4.8.1
      dotnet: none
    - mono: 4.6.1
      dotnet: none
    - mono: latest # => "stable release"
      dotnet: none
    - mono: weekly # => "latest commits"
      dotnet: none

  allow_failures:
    - mono: latest
    - mono: weekly
    - os: osx
