language: csharp
dist: xenial
sudo: false
dotnet: 2.1.505

matrix:
  fast_finish: true
  
  include:
    - os: linux
      mono: 5.8.0
    - os: linux
      mono: weekly
    - os: linux
      mono: latest
    - os: osx
      osx_image: xcode9.3
      mono: latest

  allow_failures:
    - mono: weekly
    - mono: latest

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_install:
  - dotnet tool install fake-cli -g
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1-api
  - mono .paket/paket.exe restore

script:
  - fake build
