os: Visual Studio 2015

environment:
  matrix:
    - CLI_VERSION: 1.0.0-rc4-004771

install:
  - bundle install
  # .NET Core SDK binaries
  - ps: $url = "https://dotnetcli.azureedge.net/dotnet/Sdk/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
  # Download .NET Core SDK and add to PATH
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFile = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($url, $tempFile)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFile, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
  - dotnet --info	
 
build_script:  
  - bundle exec rake
  - cmd: build.cmd

# artifacts:
#  - path: 'bin'

test: off 
version: 0.0.1.{build}
